#ifndef HAL_ADC_MODULE_ENABLED
	#define HAL_ADC_MODULE_ENABLED
#endif
#ifndef HAL_TIM_MODULE_ENABLED
	#define HAL_TIM_MODULE_ENABLED
#endif
#ifndef HAL_UART_MODULE_ENABLED
	#define HAL_UART_MODULE_ENABLED
#endif
#ifndef HAL_SPI_MODULE_ENABLED
	#define HAL_SPI_MODULE_ENABLED
#endif
#ifndef HAL_CAN_MODULE_ENABLED
	#define HAL_CAN_MODULE_ENABLED
#endif
#ifndef HAL_PCD_MODULE_ENABLED
	#define HAL_PCD_MODULE_ENABLED
#endif
#ifndef USE_USB_HS_IN_FS
	#define USE_USB_HS_IN_FS
#endif
// #ifndef HAL_DAC_MODULE_ENABLED
	// #define HAL_DAC_MODULE_ENABLED
// #endif
// #ifndef HAL_I2C_MODULE_ENABLED
	// #define HAL_I2C_MODULE_ENABLED
// #endif
