/**
 * Marlin 3D Printer Firmware
 * Copyright (c) 2020 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (c) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
#pragma once

/**
 * Standard Marlin Status Screen bitmaps
 *
 * Use the Marlin Bitmap Converter to make your own:
 * http://marlinfw.org/tools/u8glib/converter.html
 */
 ////////////////////////////////////////////////////////////////////////
/*---------------------------------------*/
/*---------RIGHT-PANEL-------------------*/
/*---------------------------------------*/
#define RIGHT_PANEL_HOME_PIC_START			0
#define RIGHT_PANEL_HOME_PIC_SIZE			2496
#define RIGHT_PANEL_CALIB_PIC_START			RIGHT_PANEL_HOME_PIC_START+RIGHT_PANEL_HOME_PIC_SIZE
#define RIGHT_PANEL_CALIB_PIC_SiZE			1643
#define RIGHT_PANEL_OPTIONS_PIC_START		RIGHT_PANEL_CALIB_PIC_START+RIGHT_PANEL_CALIB_PIC_SiZE
#define RIGHT_PANEL_OPTIONS_PIC_SIZE		3364
#define RIGHT_PANEL_LIGHT_PIC_START			RIGHT_PANEL_OPTIONS_PIC_START+RIGHT_PANEL_OPTIONS_PIC_SIZE
#define RIGHT_PANEL_LIGHT_PIC_SIZE			1848
#define RIGHT_PANEL_CAMERA_PIC_START		RIGHT_PANEL_LIGHT_PIC_START+RIGHT_PANEL_LIGHT_PIC_SIZE
#define RIGHT_PANEL_CAMERA_PIC_SIZE			2304
#define RIGHT_PANEL_FILAMENT_PIC_START		RIGHT_PANEL_CAMERA_PIC_START+RIGHT_PANEL_CAMERA_PIC_SIZE
#define RIGHT_PANEL_FILAMENT_PIC_SIZE		2760
#define RIGHT_PANEL_AXIS_PIC_START			RIGHT_PANEL_FILAMENT_PIC_START+RIGHT_PANEL_FILAMENT_PIC_SIZE
#define RIGHT_PANEL_AXIS_PIC_SIZE			2652
/*---------------------------------------*/
/*----------HOME-SCREEN------------------*/
/*---------------------------------------*/
#define GEAR_PIC_START 						RIGHT_PANEL_AXIS_PIC_START+RIGHT_PANEL_AXIS_PIC_SIZE
#define GEAR_PIC_SIZE 						41356
#define FILE_CURRENT_PIC_START 				GEAR_PIC_START+GEAR_PIC_SIZE
#define FILE_CURRENT_PIC_SIZE 				616
#define TABLE_PIC_START						FILE_CURRENT_PIC_START+FILE_CURRENT_PIC_SIZE
#define TABLE_PIC_SIZE						4080
#define HOTEND_PIC_START					TABLE_PIC_START+TABLE_PIC_SIZE
#define HOTEND_PIC_SIZE						3294
#define CHAMBER_PIC_START					HOTEND_PIC_START+HOTEND_PIC_SIZE
#define CHAMBER_PIC_SIZE					4464
#define EDIT_INC_START						CHAMBER_PIC_START+CHAMBER_PIC_SIZE
#define EDIT_INC_SIZE						441
#define DZ_SMALL_START						EDIT_INC_START+EDIT_INC_SIZE
#define DZ_SMALL_SIZE						350
#define CHECK_MARK_START					DZ_SMALL_START+DZ_SMALL_SIZE
#define CHECK_MARK_SIZE						600
#define CUBE_SMALL_START					CHECK_MARK_START+CHECK_MARK_SIZE
#define CUBE_SMALL_SIZE						396
#define BOTTOM_PANEL_FOLDER_START			CUBE_SMALL_START+CUBE_SMALL_SIZE
#define BOTTOM_PANEL_FOLDER_SIZE			2623
#define BOTTOM_PANEL_PLAY_START				BOTTOM_PANEL_FOLDER_START+BOTTOM_PANEL_FOLDER_SIZE
#define BOTTOM_PANEL_PLAY_SIZE				2378
/*---------------------------------------*/
/*----------OPT-SCREEN-------------------*/
/*---------------------------------------*/
#define AXIS_ARROW_EXLARGE_TOP_PIC_START	BOTTOM_PANEL_PLAY_START+BOTTOM_PANEL_PLAY_SIZE
#define AXIS_ARROW_EXLARGE_TOP_PIC_SIZE		3111
#define AXIS_ARROW_EXSMALL_TOP_PIC_START	AXIS_ARROW_EXLARGE_TOP_PIC_START+AXIS_ARROW_EXLARGE_TOP_PIC_SIZE
#define AXIS_ARROW_EXSMALL_TOP_PIC_SIZE		476
#define AXIS_ARROW_LARGE_TOP_PIC_START		AXIS_ARROW_EXSMALL_TOP_PIC_START+AXIS_ARROW_EXSMALL_TOP_PIC_SIZE
#define AXIS_ARROW_LARGE_TOP_PIC_SIZE		1581
#define AXIS_ARROW_SMALL_TOP_PIC_START		AXIS_ARROW_LARGE_TOP_PIC_START+AXIS_ARROW_LARGE_TOP_PIC_SIZE
#define AXIS_ARROW_SMALL_TOP_PIC_SIZE		1089
#define AXIS_EXTRUDER_SMALL_OFF_PIC_START	AXIS_ARROW_SMALL_TOP_PIC_START+AXIS_ARROW_SMALL_TOP_PIC_SIZE
#define AXIS_EXTRUDER_SMALL_OFF_PIC_SIZE	1457
#define AXIS_LETTER_DZ_LARGE_PIC_START		AXIS_EXTRUDER_SMALL_OFF_PIC_START+AXIS_EXTRUDER_SMALL_OFF_PIC_SIZE
#define AXIS_LETTER_DZ_LARGE_PIC_SIZE		1100
#define AXIS_LETTER_DZ_MEDIUM_PIC_START		AXIS_LETTER_DZ_LARGE_PIC_START+AXIS_LETTER_DZ_LARGE_PIC_SIZE
#define AXIS_LETTER_DZ_MEDIUM_PIC_SIZE		595
#define AXIS_LETTER_X_LARGE_PIC_START		AXIS_LETTER_DZ_MEDIUM_PIC_START+AXIS_LETTER_DZ_MEDIUM_PIC_SIZE
#define AXIS_LETTER_X_LARGE_PIC_SIZE		1015
#define AXIS_LETTER_X_MEDIUM_PIC_START		AXIS_LETTER_X_LARGE_PIC_START+AXIS_LETTER_X_LARGE_PIC_SIZE
#define AXIS_LETTER_X_MEDIUM_PIC_SIZE		340
#define AXIS_LETTER_Y_LARGE_PIC_START		AXIS_LETTER_X_MEDIUM_PIC_START+AXIS_LETTER_X_MEDIUM_PIC_SIZE
#define AXIS_LETTER_Y_LARGE_PIC_SIZE		1085
#define AXIS_LETTER_Y_MEDIUM_PIC_START		AXIS_LETTER_Y_LARGE_PIC_START+AXIS_LETTER_Y_LARGE_PIC_SIZE
#define AXIS_LETTER_Y_MEDIUM_PIC_SIZE		357
#define AXIS_LETTER_Z_LARGE_PIC_START		AXIS_LETTER_Y_MEDIUM_PIC_START+AXIS_LETTER_Y_MEDIUM_PIC_SIZE
#define AXIS_LETTER_Z_LARGE_PIC_SIZE		1015
#define AXIS_LETTER_Z_MEDIUM_PIC_START		AXIS_LETTER_Z_LARGE_PIC_START+AXIS_LETTER_Z_LARGE_PIC_SIZE
#define AXIS_LETTER_Z_MEDIUM_PIC_SIZE		340
#define AXIS_EXTRUDER_EXSMALL_PIC_START		AXIS_LETTER_Z_MEDIUM_PIC_START+AXIS_LETTER_Z_MEDIUM_PIC_SIZE
#define AXIS_EXTRUDER_EXSMALL_PIC_SIZE		400
/*---------------------------------------*/
/*----------NUM-SCREEN-------------------*/
/*---------------------------------------*/
#define NUM_PIC_OK_START					AXIS_EXTRUDER_EXSMALL_PIC_START+AXIS_EXTRUDER_EXSMALL_PIC_SIZE
#define NUM_PIC_OK_SIZE						1156
#define NUM_PIC_CANCEL_START				NUM_PIC_OK_START+NUM_PIC_OK_SIZE
#define NUM_PIC_CANCEL_SIZE					1156
#define NUM_PIC_BACK_START					NUM_PIC_CANCEL_START+NUM_PIC_CANCEL_SIZE
#define NUM_PIC_BACK_SIZE					1173
#define NUM_PIC_ONE_START					NUM_PIC_BACK_START+NUM_PIC_BACK_SIZE
#define NUM_PIC_ONE_SIZE					260
#define NUM_PIC_TWO_START					NUM_PIC_ONE_START+NUM_PIC_ONE_SIZE
#define NUM_PIC_TWO_SIZE					320
#define NUM_PIC_THREE_START					NUM_PIC_TWO_START+NUM_PIC_TWO_SIZE
#define NUM_PIC_THREE_SIZE					336
#define NUM_PIC_FOUR_START					NUM_PIC_THREE_START+NUM_PIC_THREE_SIZE
#define NUM_PIC_FOUR_SIZE					378
#define NUM_PIC_FIVE_START					NUM_PIC_FOUR_START+NUM_PIC_FOUR_SIZE
#define NUM_PIC_FIVE_SIZE					340
#define NUM_PIC_SIX_START					NUM_PIC_FIVE_START+NUM_PIC_FIVE_SIZE
#define NUM_PIC_SIX_SIZE					357
#define NUM_PIC_SEVEN_START					NUM_PIC_SIX_START+NUM_PIC_SIX_SIZE
#define NUM_PIC_SEVEN_SIZE					300
#define NUM_PIC_EIGHT_START					NUM_PIC_SEVEN_START+NUM_PIC_SEVEN_SIZE
#define NUM_PIC_EIGHT_SIZE					340
#define NUM_PIC_NINE_START					NUM_PIC_EIGHT_START+NUM_PIC_EIGHT_SIZE
#define NUM_PIC_NINE_SIZE					340
#define NUM_PIC_ZERO_START					NUM_PIC_NINE_START+NUM_PIC_NINE_SIZE
#define NUM_PIC_ZERO_SIZE					340
/*---------------------------------------*/
/*----------CALIB-SCREEN-----------------*/
/*---------------------------------------*/
#define CALIB_SPEED_PIC_START				NUM_PIC_ZERO_START+NUM_PIC_ZERO_SIZE
#define CALIB_SPEED_PIC_SIZE				3318
#define CALIB_COOLER_PIC_START				CALIB_SPEED_PIC_START+CALIB_SPEED_PIC_SIZE
#define CALIB_COOLER_PIC_SIZE				3306


#define RIGHT_PANEL_HOME_X 726
#define RIGHT_PANEL_HOME_Y 34
#define RIGHT_PANEL_HOME_WIDTH  48
#define RIGHT_PANEL_HOME_HEIGHT 52
#define RIGHT_PANEL_CALIB_X 721
#define RIGHT_PANEL_CALIB_Y 109
#define RIGHT_PANEL_CALIB_WIDTH 53
#define RIGHT_PANEL_CALIB_HEIGHT 31
#define RIGHT_PANEL_OPTIONS_X 719
#define RIGHT_PANEL_OPTIONS_Y 167
#define RIGHT_PANEL_OPTIONS_WIDTH 58
#define RIGHT_PANEL_OPTIONS_HEIGHT 58
#define RIGHT_PANEL_LIGHT_X 731
#define RIGHT_PANEL_LIGHT_Y 247
#define RIGHT_PANEL_LIGHT_WIDTH 33
#define RIGHT_PANEL_LIGHT_HEIGHT 56
#define RIGHT_PANEL_CAMERA_X 718
#define RIGHT_PANEL_CAMERA_Y 350
#define RIGHT_PANEL_CAMERA_WIDTH 64
#define RIGHT_PANEL_CAMERA_HEIGHT 36
#define RIGHT_PANEL_FILAMENT_X 717
#define RIGHT_PANEL_FILAMENT_Y 421
#define RIGHT_PANEL_FILAMENT_WIDTH 60
#define RIGHT_PANEL_FILAMENT_HEIGHT 46
#define RIGHT_PANEL_AXIS_X 720
#define RIGHT_PANEL_AXIS_Y 503
#define RIGHT_PANEL_AXIS_WIDTH 52
#define RIGHT_PANEL_AXIS_HEIGHT 51

#ifndef STATUS_BED_X
	#define STATUS_BED_X   458//(LCD_PIXEL_WIDTH - (STATUS_BED_WIDTH + STATUS_CHAMBER_WIDTH + STATUS_FAN_WIDTH) )
#endif
#ifndef STATUS_BED_Y
	#define STATUS_BED_Y 	(STATUS_HOTEND_Y(EXTRUDERS-1) + STATUS_HEATERS_YSPACE)
#endif
#ifndef STATUS_CHAMBER_X
	#define STATUS_CHAMBER_X   458//(LCD_PIXEL_WIDTH - (STATUS_BED_WIDTH + STATUS_CHAMBER_WIDTH + STATUS_FAN_WIDTH) )
#endif
#ifndef STATUS_CHAMBER_Y
	#define STATUS_CHAMBER_Y 	(STATUS_BED_Y + STATUS_HEATERS_YSPACE)
#endif

#ifndef STATUS_BED_TEXT_X
	#define STATUS_BED_TEXT_X (STATUS_BED_X + 158)
#endif

#ifndef STATUS_BED_TEXT_Y
	#define STATUS_BED_TEXT_Y (STATUS_BED_Y + 27)
#endif

#ifndef STATUS_CHAMBER_TEXT_X
	#define STATUS_CHAMBER_TEXT_X (STATUS_BED_TEXT_X)
#endif

#ifndef STATUS_CHAMBER_TEXT_Y
	#define STATUS_CHAMBER_TEXT_Y (STATUS_BED_TEXT_Y + STATUS_HEATERS_YSPACE)
#endif

#ifndef STATUS_HEATERS_X
	#define STATUS_HEATERS_X 458
#endif
#ifndef STATUS_HEATERS_XSPACE
	#define STATUS_HEATERS_XSPACE 0
#endif
#ifndef STATUS_HEATERS_YSPACE
	#define STATUS_HEATERS_YSPACE 99
#endif
#ifndef STATUS_HEATERS_Y
	#define STATUS_HEATERS_Y 28
#endif




#define GEAR_PIC_X 101
#define GEAR_PIC_Y 104
#define GEAR_PIC_WIDTH  196
#define GEAR_PIC_HEIGHT 211

#define FILE_CURRENT_PIC_X 41
#define FILE_CURRENT_PIC_Y 43
#define BOTTOM_PANEL_FOLDER_X 58
#define BOTTOM_PANEL_FOLDER_Y 507
#define BOTTOM_PANEL_PLAY_X 240
#define BOTTOM_PANEL_PLAY_Y 508

#ifndef BOTTOM_PANEL_PIC_X
	#define BOTTOM_PANEL_PIC_X 24
#endif
#ifndef BOTTOM_PANEL_PIC_Y
	#define BOTTOM_PANEL_PIC_Y 430
#endif
// #define BOTTOM_PANEL_PIC_WIDTH  677
////////////////////////////////////////////////////////////////////////
#ifndef HOTEND_PIC_WIDTH
	#define HOTEND_PIC_WIDTH 54
#endif
#ifndef HOTEND_PIC_HEIGHT
	#define HOTEND_PIC_HEIGHT 61
#endif
#ifndef TABLE_PIC_WIDTH
	#define TABLE_PIC_WIDTH 68
#endif
#ifndef TABLE_PIC_HEIGHT
	#define TABLE_PIC_HEIGHT 60
#endif
#ifndef CHAMBER_PIC_WIDTH
	#define CHAMBER_PIC_WIDTH 72
#endif
#ifndef CHAMBER_PIC_HEIGHT
	#define CHAMBER_PIC_HEIGHT 62
#endif